import { Product } from "../modules/products/models/product.model";
import { ProductCategory } from "../modules/products/product.types";

export const seedProducts = async (): Promise<void> => {
    console.log("🗑 Clearing existing products...");

    await Product.deleteMany({});

    const products = [
        {
            name: "HP ProBook 450 G10",
            sku: "PRD001",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 65000,
            sellingPrice: 72000,
            stockQuantity: 15,
            image: "https://picsum.photos/seed/product1/400/400",
        },
        {
            name: "Dell Inspiron 15",
            sku: "PRD002",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 58000,
            sellingPrice: 64000,
            stockQuantity: 12,
            image: "https://picsum.photos/seed/product2/400/400",
        },
        {
            name: "Logitech G102 Mouse",
            sku: "PRD003",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 1200,
            sellingPrice: 1800,
            stockQuantity: 50,
            image: "https://picsum.photos/seed/product3/400/400",
        },
        {
            name: "Redragon K552 Keyboard",
            sku: "PRD004",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 2800,
            sellingPrice: 3500,
            stockQuantity: 25,
            image: "https://picsum.photos/seed/product4/400/400",
        },
        {
            name: "Samsung 24 Monitor",
            sku: "PRD005",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 13500,
            sellingPrice: 15500,
            stockQuantity: 8,
            image: "https://picsum.photos/seed/product5/400/400",
        },
        {
            name: "Canon PIXMA Printer",
            sku: "PRD006",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 8500,
            sellingPrice: 9800,
            stockQuantity: 6,
            image: "https://picsum.photos/seed/product6/400/400",
        },
        {
            name: "Kingston SSD 500GB",
            sku: "PRD007",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 4200,
            sellingPrice: 5200,
            stockQuantity: 30,
            image: "https://picsum.photos/seed/product7/400/400",
        },
        {
            name: "Apple AirPods Pro",
            sku: "PRD008",
            category: ProductCategory.ELECTRONICS,
            purchasePrice: 18000,
            sellingPrice: 22000,
            stockQuantity: 7,
            image: "https://picsum.photos/seed/product8/400/400",
        },
        {
            name: "Basmati Rice 5kg",
            sku: "PRD009",
            category: ProductCategory.GROCERY,
            purchasePrice: 750,
            sellingPrice: 920,
            stockQuantity: 40,
            image: "https://picsum.photos/seed/product9/400/400",
        },
        {
            name: "Sunflower Oil 5L",
            sku: "PRD010",
            category: ProductCategory.GROCERY,
            purchasePrice: 820,
            sellingPrice: 980,
            stockQuantity: 35,
            image: "https://picsum.photos/seed/product10/400/400",
        },
        {
            name: "Fresh Milk 1L",
            sku: "PRD011",
            category: ProductCategory.GROCERY,
            purchasePrice: 70,
            sellingPrice: 90,
            stockQuantity: 60,
            image: "https://picsum.photos/seed/product11/400/400",
        },
        {
            name: "Men's Polo Shirt",
            sku: "PRD012",
            category: ProductCategory.FASHION,
            purchasePrice: 550,
            sellingPrice: 850,
            stockQuantity: 18,
            image: "https://picsum.photos/seed/product12/400/400",
        },
        {
            name: "Women's Hoodie",
            sku: "PRD013",
            category: ProductCategory.FASHION,
            purchasePrice: 850,
            sellingPrice: 1200,
            stockQuantity: 10,
            image: "https://picsum.photos/seed/product13/400/400",
        },
        {
            name: "Sneakers",
            sku: "PRD014",
            category: ProductCategory.FASHION,
            purchasePrice: 1800,
            sellingPrice: 2500,
            stockQuantity: 5,
            image: "https://picsum.photos/seed/product14/400/400",
        },
        {
            name: "A4 Paper",
            sku: "PRD015",
            category: ProductCategory.STATIONERY,
            purchasePrice: 320,
            sellingPrice: 450,
            stockQuantity: 80,
            image: "https://picsum.photos/seed/product15/400/400",
        },
        {
            name: "Notebook",
            sku: "PRD016",
            category: ProductCategory.STATIONERY,
            purchasePrice: 40,
            sellingPrice: 60,
            stockQuantity: 100,
            image: "https://picsum.photos/seed/product16/400/400",
        },
        {
            name: "Blue Ball Pen",
            sku: "PRD017",
            category: ProductCategory.STATIONERY,
            purchasePrice: 8,
            sellingPrice: 15,
            stockQuantity: 250,
            image: "https://picsum.photos/seed/product17/400/400",
        },
        {
            name: "Whiteboard Marker",
            sku: "PRD018",
            category: ProductCategory.STATIONERY,
            purchasePrice: 25,
            sellingPrice: 40,
            stockQuantity: 120,
            image: "https://picsum.photos/seed/product18/400/400",
        },
        {
            name: "Gift Box",
            sku: "PRD019",
            category: ProductCategory.OTHER,
            purchasePrice: 90,
            sellingPrice: 150,
            stockQuantity: 25,
            image: "https://picsum.photos/seed/product19/400/400",
        },
        {
            name: "Water Bottle",
            sku: "PRD020",
            category: ProductCategory.OTHER,
            purchasePrice: 120,
            sellingPrice: 180,
            stockQuantity: 4,
            image: "https://picsum.photos/seed/product20/400/400",
        },
    ];

    await Product.insertMany(products);

    console.log("=================================");
    console.log("✅ 20 Products Seeded Successfully");
    console.log("=================================");
};